### ISSUE TITLE
Portar Ikemen plus Ultra al lenguaje C

### ISSUE THREAD

**Issue by sfz3mix** [CableDorado2/Ikemen-Plus-Ultra#12]
Si se quiere portar la versión final a Linux, MacOS, Android e iOS, sería mucho más fácil si el motor estuviera escrito en C.
Otra cosa buena de estar en C es que podrías hacer un core (motor principal) para Retroarch y automáticamente funcionaría en docenas de plataformas y también tendrías soporte para jugar online en Retroarch.
Todo lo que tendrías que hacer es cargar el núcleo (motor) y luego, como una rom de consola, un .zip con chars, escenarios, música y demás.

Tenga en cuenta las ventajas. 

Atentamente Zero800

**Comment by CableDorado2** [comment]
Antes que nada, quiero aclarar que no soy el autor original del motor, solo estoy actualizando con ayuda de otros usuarios lo que quedó por internet del motor original (Ikemen Plus).

Ahora me pregunto, ¿necesariamente el motor debe estar escrito en C para realizar este tipo de porteos a multiplataformas? porque el ejecutable que se genera para windows entiendo que está escrito en C++. En el directorio src/alpha/sdlplugin/sdlplugin puede observarlo en el archivo del proyecto llamado ssize que carga el main.cpp.

Por cuestiones de compatibilidad se debe usar Microsoft Visual C++ 2010 Express para compilarlo.

Pronto cuando esté en las fases finales de mis planes con este motor, estaré estudiando más sobre los porteos a multiplataformas ya que por los momentos, me he centrado en la codificación de scripts por el lenguaje lua para integrar las funcionalidades que me he ido planteando.
