### ISSUE TITLE
Make Menu Controls Separate from In-Game Controls

### ISSUE THREAD

**Issue by shinra358** [CableDorado2/Ikemen-Plus-Ultra#5]
Changing input will also change menu input. I don't want the menu input switching to another button so can we have them separate so it won't be hard navigating after changing buttons?

**Comment by wrzxw** [comment]
Ask him to add a separate option for menu input and In-Game controls, or try coding it by yourself

**Comment by CableDorado2** [comment]
> Changing input will also change menu input. I don't want the menu input switching to another button so can we have them separate so it won't be hard navigating after changing buttons?

Already done in v1.4
